AWSTemplateFormatVersion: "2010-09-09"

Parameters:

  BucketName:
    Type: String
#    Default: babbelfish-app-bucket1
    Description: The name of the bucket where zip file is placed

Resources:
  VoiceTranslatorBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
        #WebsiteConfiguration:
        #IndexDocument: voice-translator.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET,PUT,POST,HEAD]
            AllowedOrigins: ['*']
            Id: myCORSRuleId1
            MaxAge: '3600'

# Bucket Policy to allow Origin Access Identity to get and put objects to private S3 bucket
  VoiceTranslatorBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref VoiceTranslatorBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Principal:
              CanonicalUser: !GetAtt CloudfrontoOriginAccessIdentity.S3CanonicalUserId
            Action: ['s3:GetObject', 's3:GetObjectAcl', 's3:PutObject', 's3:PutObjectAcl']
            Effect: Allow
            Resource:
              - !Join ['', ['arn:aws:s3:::', !Ref VoiceTranslatorBucket, '/*']]

# Lambda function setup that would use jar present in S3 bucket that would perform all the logic
  VoiceTranslatorLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      Description: "Handle input audio and transcribe, translate and convert back to audio"
      Handler: "app.babelfish.LambdaHandler::handleRequest"
      Role: !GetAtt VoiceTranslatorLambdaRole.Arn
      Code:
        S3Bucket: !Sub ${BucketName}
        S3Key: 'babel-fish-app-1.0-SNAPSHOT.jar'
      Runtime: "java8"
      MemorySize: 1024
      Timeout: 30

# Create Lambda role that would allow lambda to use transcribe, translate, polly and S3 services
  VoiceTranslatorLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: TranscribeAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "transcribe:StartStreamTranscription"
                Resource: "*"
        - PolicyName: CloudWatchPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
        - PolicyName: TranslateAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "translate:TranslateText"
                Resource: "*"
        - PolicyName: PollyAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "polly:SynthesizeSpeech"
                Resource: "*"
        - PolicyName: S3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:PutObjectAcl"
                Resource:
                  Fn::Join: ["",["arn:aws:s3:::", !Ref VoiceTranslatorBucket, "/*"]]
        - PolicyName: S3LocationAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetBucketLocation"
                Resource: "arn:aws:s3:::*"

# Setup Origin Access Identity that would allow cloud distribution to access private S3
  CloudfrontoOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'origin-access-identity-for-s3-bucket'

# Cloud distribution to let users access application front end over internet. Generate url is available
#  as output parameters
  CfDistribution:
    Metadata:
      Comment: 'CloudFront distribution over Voice Translator App - to enable HTTPS'
    Properties:
      DistributionConfig:
        Comment: 'CloudFront distribution over Voice Translator App - to enable HTTPS'
        DefaultCacheBehavior:
          AllowedMethods:
            - 'HEAD'
            - 'GET'
            - 'PUT'
            - 'POST'
            - 'OPTIONS'
            - 'DELETE'
            - 'PATCH'
          CachedMethods:
            - 'HEAD'
            - 'GET'
          Compress: false
          DefaultTTL: 86400
          ForwardedValues:
            Cookies:
              Forward: 'none'
            Headers:
              - 'Origin'
            QueryString: false
#          DefaultTTL: 0
          TargetOriginId: !Ref VoiceTranslatorBucket
          ViewerProtocolPolicy: 'redirect-to-https'
        DefaultRootObject: 'index.html'
        Enabled: true
        HttpVersion: 'http1.1'
        IPV6Enabled: false
        Origins:
          - DomainName: !Join ["",[!Ref VoiceTranslatorBucket, ".s3.amazonaws.com"]]
            Id: !Ref VoiceTranslatorBucket
            S3OriginConfig: {
              OriginAccessIdentity:
                !Join ["",["origin-access-identity/cloudfront/", !Ref CloudfrontoOriginAccessIdentity]]
            }
        PriceClass: 'PriceClass_All'
    Type: 'AWS::CloudFront::Distribution'


  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      AllowUnauthenticatedIdentities: True


  IdentityPoolRoleMapping:
    Type: "AWS::Cognito::IdentityPoolRoleAttachment"
    Properties:
      IdentityPoolId: !Ref CognitoIdentityPool
      Roles:
        unauthenticated: !GetAtt CognitoUnAuthorizedRole.Arn

  CognitoUnAuthorizedRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Federated: "cognito-identity.amazonaws.com"
            Action:
              - "sts:AssumeRoleWithWebIdentity"
      Policies:
        - PolicyName: "CognitoUnauthorizedPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "lambda:InvokeFunction"
                Resource:
                  - !GetAtt VoiceTranslatorLambda.Arn
              - Effect: Allow
                Action:
                  - "s3:PutObject"
                Resource:
                  Fn::Join:
                    - ""
                    -
                      - "arn:aws:s3:::"
                      -  Ref: VoiceTranslatorBucket
                      - "/*"

Outputs:
  VoiceTranslatorLink:
    Description: 'Domain name for our cloudfront distribution'
    Value: !Join [ "", [ "https://", !GetAtt CfDistribution.DomainName, "/voice-translator.html" ] ]
  VoiceTranslatorBucket:
    Description: VoiceTranslator S3 Bucket
    Value: !Ref VoiceTranslatorBucket
  IdentityPoolIdOutput:
    Description: IdentityPoolId
    Value: !Ref CognitoIdentityPool
  VoiceTranslatorLambda:
    Description: VoiceTranslator Lambda
    Value: !Ref VoiceTranslatorLambda
